#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ -z "$BROWSER" && "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

if [[ -z "$EDITOR" ]]; then
  export EDITOR='vim'
fi
if [[ -z "$VISUAL" ]]; then
  export VISUAL='vim'
fi
if [[ -z "$PAGER" ]]; then
  export PAGER='less'
fi

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/.local/{,s}bin(N)
  /opt/{homebrew,local}/{,s}bin(N)
  /usr/local/{,s}bin(N)
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X to enable it.
if [[ -z "$LESS" ]]; then
  export LESS='-g -i -M -R -S -w -X -z-4'
fi

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if [[ -z "$LESSOPEN" ]] && (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Aliases
#
alias pa='php artisan'
alias tinker='php artisan tinker'
alias phpunit='vendor/bin/phpunit'

alias ruby-cli='irb'

alias redis-cli='redis-cli -p 6793'

alias pm='python manage.py'
alias workin='source env/bin/activate'

alias docker='podman'
alias docker-compose='podman-compose'

#
# Others
#

if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    export MOZ_ENABLE_WAYLAND=1
fi

# add ASDF
export ASDF_DIR="$HOME/.asdf"
[[ -d "$ASDF_DIR" ]] && source "$ASDF_DIR/asdf.sh"

# node env
export PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules

# Some prompt options
export DEFAULT_USER="$USER"
export VIRTUAL_ENV_DISABLE_PROMPT=0

# REMOVE Qt Warnings
# Export QT_LOGGING_RULES='*.debug=false'
export QT_LOGGING_RULES='*=false'

# Force Krita use default style
export KRITA_NO_STYLE_OVERRIDE=1

# To ignore the whitelist and allow support for other drivers
export GST_VAAPI_ALL_DRIVERS=1

# Completion
setopt COMPLETE_ALIASES
