#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# composer env (laravel, etc)
export PATH="$HOME/.composer/bin:$HOME/.composer/vendor/bin:$PATH"

# ruby env
if [[ -d "$HOME/.rbenv" ]]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
  eval "$(rbenv init -)"
fi

# python env
export WORKON_HOME=~/.virtualenvs
export VIRTUALENVWRAPPER_VIRTUALENV_ARGS='--no-site-packages --python=/usr/bin/python3'
[[ -f '/usr/bin/virtualenvwrapper.sh' ]] && source '/usr/bin/virtualenvwrapper.sh'

# node env
export PATH="$HOME/.node_modules/bin:$PATH"
export npm_config_prefix=~/.node_modules

# added by travis gem
[[ -f "$HOME/.travis/travis.sh" ]] && source "$HOME/.travis/travis.sh"

# Some prompt options
export DEFAULT_USER="$USER"
export VIRTUAL_ENV_DISABLE_PROMPT=0

# Aliases
alias pa='php artisan'
alias tinker='php artisan tinker'
alias phpunit='vendor/bin/phpunit'

alias ruby-cli='irb'

alias redis-cli='redis-cli -p 6793'

alias pm='python manage.py'
alias workin='source env/bin/activate'
